-- PROTOTYPE GENERATED by :QuickBind.
--
-- Safe to inspect, but prefer changing entries through :QuickBind, :QuickBindDelete,
-- :QuickBindEdit, and :QuickBindReload. The quickbinder rewrites this whole file.

return {
  version = 1,
  groups = {
    { lhs = "<leader>b", desc = "buffer" },
  },
  binds = {
    { lhs = "<leader>L", modes = { "n", "x" }, action = "command.Lazy", desc = "Lazy" },
    { lhs = "<leader><tab>", modes = { "n", "x" }, action = "command.BufferPick", desc = "BufferPick" },
    { lhs = "<leader>-", modes = { "n", "x" }, action = "command.Restart", desc = "Restart Neovim" },
    { lhs = "<leader>bd", mode = "n", action = "command.BufferClose", desc = "BufferClose" },
  },
}
