-- PROTOTYPE: comprehensive which-key quickbinder.
--
-- Question this answers: can Neovim get close to Obsidian Spacekeys' quick bind
-- workflow without letting a script rewrite hand-authored keymap.lua?
--
-- Design constraints:
--   * hand-written keymaps stay in lua/config/keymap.lua
--   * generated bindings live in lua/config/quickbind_generated.lua
--   * generated entries save stable action ids, not Lua source
--   * which-key is used as the display layer, not as a config editor
--
-- Docs worth reading before hardening this beyond prototype:
--   :h vim.keymap.set()
--   :h vim.ui.select()
--   :h vim.ui.input()
--   :h maparg()
--   :h mapcheck()
--   :h nvim_create_user_command()
--   :h which-key.nvim-which-key-mappings

-- TODO add support for :Command [arg] ie :CellularAutomation make_it_rain
local M = {}

local state = {
  opts = nil,
  generated = nil,
  actions = {},
  actions_by_id = {},
}

local defaults = {
  generated_path = vim.fs.joinpath(vim.fn.stdpath("config"), "lua", "config", "quickbind_generated.lua"),
  default_groups = {
    { lhs = "<leader>k", desc = "keybinds" },
  },
}

local valid_modes = {
  n = true,
  x = true,
  v = true,
  s = true,
  o = true,
  i = true,
  t = true,
  c = true,
}

local function notify(message, level)
  vim.notify("[quickbind] " .. message, level or vim.log.levels.INFO)
end

local function trim(value)
  return (value or ""):gsub("^%s+", ""):gsub("%s+$", "")
end

local function cmd(command)
  return "<cmd>" .. command .. "<CR>"
end

local function is_empty(tbl)
  return type(tbl) ~= "table" or next(tbl) == nil
end

local function as_list(value)
  if value == nil then
    return {}
  end
  if type(value) == "table" then
    return value
  end
  return { value }
end

local function mode_list(entry, fallback)
  if entry.modes then
    return as_list(entry.modes)
  end
  if entry.mode then
    return as_list(entry.mode)
  end
  if fallback and fallback.modes then
    return as_list(fallback.modes)
  end
  if fallback and fallback.mode then
    return as_list(fallback.mode)
  end
  return { "n" }
end

local function parse_modes(input, fallback)
  local raw = trim(input)
  if raw == "" then
    raw = fallback or "n"
  end

  raw = raw:gsub("%s+", "")
  local modes = {}

  if raw:find(",", 1, true) then
    for mode in raw:gmatch("[^,]+") do
      modes[#modes + 1] = mode
    end
  else
    for i = 1, #raw do
      modes[#modes + 1] = raw:sub(i, i)
    end
  end

  local seen = {}
  local normalized = {}
  for _, mode in ipairs(modes) do
    if not valid_modes[mode] then
      return nil, "invalid mode `" .. mode .. "`"
    end
    if not seen[mode] then
      seen[mode] = true
      normalized[#normalized + 1] = mode
    end
  end

  return normalized
end

local function quote(value)
  return string.format("%q", value)
end

local function write_generated(data)
  local lines = {
    "-- PROTOTYPE GENERATED by :QuickBind.",
    "--",
    "-- Safe to inspect, but prefer changing entries through :QuickBind, :QuickBindDelete,",
    "-- :QuickBindEdit, and :QuickBindReload. The quickbinder rewrites this whole file.",
    "",
    "return {",
    "  version = 1,",
    "  groups = {",
  }

  for _, group in ipairs(data.groups or {}) do
    lines[#lines + 1] = ("    { lhs = %s, desc = %s },"):format(quote(group.lhs), quote(group.desc))
  end

  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "  binds = {"

  for _, bind in ipairs(data.binds or {}) do
    local fields = {
      "lhs = " .. quote(bind.lhs),
    }

    local modes = mode_list(bind)
    if #modes == 1 then
      fields[#fields + 1] = "mode = " .. quote(modes[1])
    else
      local mode_parts = {}
      for _, mode in ipairs(modes) do
        mode_parts[#mode_parts + 1] = quote(mode)
      end
      fields[#fields + 1] = "modes = { " .. table.concat(mode_parts, ", ") .. " }"
    end

    if bind.action then
      fields[#fields + 1] = "action = " .. quote(bind.action)
    end
    if bind.rhs then
      fields[#fields + 1] = "rhs = " .. quote(bind.rhs)
    end
    if bind.desc then
      fields[#fields + 1] = "desc = " .. quote(bind.desc)
    end

    lines[#lines + 1] = "    { " .. table.concat(fields, ", ") .. " },"
  end

  lines[#lines + 1] = "  },"
  lines[#lines + 1] = "}"
  lines[#lines + 1] = ""

  vim.fn.mkdir(vim.fs.dirname(state.opts.generated_path), "p")
  vim.fn.writefile(lines, state.opts.generated_path)
end

local function normalize_generated(data)
  data = type(data) == "table" and data or {}
  data.groups = type(data.groups) == "table" and data.groups or {}
  data.binds = type(data.binds) == "table" and data.binds or {}
  data.version = data.version or 1
  return data
end

local function load_generated()
  local path = state.opts.generated_path
  if not vim.uv.fs_stat(path) then
    local data = normalize_generated({})
    write_generated(data)
    return data
  end

  local chunk, load_error = loadfile(path)
  if not chunk then
    notify("could not load generated file: " .. load_error, vim.log.levels.ERROR)
    return normalize_generated({})
  end

  local ok, data = pcall(chunk)
  if not ok then
    notify("generated file errored: " .. data, vim.log.levels.ERROR)
    return normalize_generated({})
  end

  return normalize_generated(data)
end

local function tokens(lhs)
  local result = {}
  local i = 1
  while i <= #lhs do
    local char = lhs:sub(i, i)
    if char == "<" then
      local close = lhs:find(">", i, true)
      if close then
        result[#result + 1] = lhs:sub(i, close)
        i = close + 1
      else
        result[#result + 1] = char
        i = i + 1
      end
    else
      result[#result + 1] = char
      i = i + 1
    end
  end
  return result
end

local function join_tokens(parts, stop)
  local out = {}
  for i = 1, stop or #parts do
    out[#out + 1] = parts[i]
  end
  return table.concat(out, "")
end

local function display_lhs(lhs)
  local parts = tokens(lhs)
  if parts[1] and parts[1]:lower() == "<leader>" then
    local rest = {}
    for i = 2, #parts do
      rest[#rest + 1] = parts[i]
    end
    if #rest == 0 then
      return "SPC"
    end
    return "SPC " .. table.concat(rest, " ")
  end
  return table.concat(parts, " ")
end

local function normalize_lhs(input)
  local value = trim(input)
  if value == "" then
    return nil
  end

  local lower = value:lower()
  if lower:match("^spc%s+") then
    return "<leader>" .. value:gsub("^%S+%s+", ""):gsub("%s+", "")
  end
  if lower:match("^space%s+") then
    return "<leader>" .. value:gsub("^%S+%s+", ""):gsub("%s+", "")
  end
  if lower:match("^leader%s+") then
    return "<leader>" .. value:gsub("^%S+%s+", ""):gsub("%s+", "")
  end
  if lower:sub(1, 8) == "<space>" then
    return "<leader>" .. value:sub(8):gsub("%s+", "")
  end
  if lower:sub(1, 8) == "<leader>" then
    return "<leader>" .. value:gsub("^<[Ll]eader>", ""):gsub("%s+", "")
  end
  if value:sub(1, 1) == "<" then
    return value:gsub("%s+", "")
  end
  if value:sub(1, 1) == " " then
    return "<leader>" .. value:sub(2):gsub("%s+", "")
  end

  return "<leader>" .. value:gsub("%s+", "")
end

local function group_prefixes(lhs)
  local parts = tokens(lhs)
  if not parts[1] or parts[1]:lower() ~= "<leader>" then
    return {}
  end

  local prefixes = {}
  for i = 2, #parts - 1 do
    prefixes[#prefixes + 1] = join_tokens(parts, i)
  end
  return prefixes
end

local function maparg(lhs, mode)
  local ok, result = pcall(vim.fn.maparg, lhs, mode, false, true)
  if not ok or is_empty(result) or not result.lhs or result.lhs == "" then
    return nil
  end
  return result
end

local function is_which_key_trigger(mapping)
  local desc = mapping.desc or ""
  local rhs = mapping.rhs or ""
  return desc == "which-key-trigger" or rhs:find("which%-key", 1, false) ~= nil
end

local function map_summary(mapping)
  if not mapping then
    return ""
  end
  if mapping.desc and mapping.desc ~= "" then
    return mapping.desc
  end
  if mapping.rhs and mapping.rhs ~= "" then
    return mapping.rhs
  end
  if mapping.callback then
    return "Lua callback"
  end
  return "existing mapping"
end

local function generated_group_map(data)
  local groups = {}
  for _, group in ipairs(defaults.default_groups) do
    groups[group.lhs] = group.desc
  end
  for _, group in ipairs(data.groups or {}) do
    groups[group.lhs] = group.desc
  end
  return groups
end

local function has_group(data, lhs)
  return generated_group_map(data)[lhs] ~= nil
end

local function add_group(data, lhs, desc)
  if has_group(data, lhs) then
    return
  end
  data.groups[#data.groups + 1] = { lhs = lhs, desc = desc }
end

local function register_groups(data)
  local ok, wk = pcall(require, "which-key")
  if not ok then
    return
  end

  local specs = {}
  local seen = {}
  for _, group in ipairs(defaults.default_groups) do
    specs[#specs + 1] = { group.lhs, group = group.desc }
    seen[group.lhs] = true
  end
  for _, group in ipairs(data.groups or {}) do
    if group.lhs and group.desc and not seen[group.lhs] then
      specs[#specs + 1] = { group.lhs, group = group.desc }
      seen[group.lhs] = true
    end
  end

  if #specs > 0 then
    wk.add(specs)
  end
end

local function refresh_actions()
  local ok, registry = pcall(require, "config.quickbind_actions")
  if not ok then
    notify("could not load action registry: " .. registry, vim.log.levels.ERROR)
    return
  end

  state.actions = registry.build()
  state.actions_by_id = {}
  for _, action in ipairs(state.actions) do
    if action.id and not state.actions_by_id[action.id] then
      state.actions_by_id[action.id] = action
    end
  end
end

local function action_label(action)
  local mode = table.concat(mode_list(action), "")
  return ("%-18s %-8s %s  ·  %s"):format(action.category or "misc", mode, action.desc or action.id, action.id)
end

local function resume(co, ...)
  local status = coroutine.status(co)
  if status == "dead" then
    return
  end

  -- :h vim.ui.input() allows UI implementations to call their callback before
  -- returning. The built-in UI does this, so callback-driven code can still be
  -- inside this coroutine. Schedule that resume for the next loop tick so the
  -- coroutine reaches coroutine.yield() first.
  if status == "running" then
    local args = { n = select("#", ...), ... }
    vim.schedule(function()
      resume(co, unpack(args, 1, args.n))
    end)
    return
  end

  local ok, err = coroutine.resume(co, ...)
  if not ok then
    notify(debug.traceback(co, err), vim.log.levels.ERROR)
  end
end

local function run_async(fn)
  local co = coroutine.create(fn)
  resume(co)
end

local function select_async(prompt, items, format_item)
  if #items == 0 then
    return nil
  end

  local co = coroutine.running()

  vim.ui.select(items, {
    prompt = prompt,
    format_item = format_item,
  }, function(choice)
    resume(co, choice)
  end)

  return coroutine.yield()
end

local function input_async(prompt, default)
  local co = coroutine.running()
  vim.ui.input({
    prompt = prompt,
    default = default,
  }, function(input)
    resume(co, input)
  end)
  return coroutine.yield()
end

local function confirm_async(prompt, choices)
  return select_async(prompt, choices or { "Cancel", "Continue" }, function(choice)
    return choice
  end)
end

local function validate_lhs(lhs, modes)
  local result = {
    exact = {},
    blocked = {},
  }

  for _, mode in ipairs(modes) do
    local exact = maparg(lhs, mode)
    if exact and not is_which_key_trigger(exact) then
      result.exact[#result.exact + 1] = {
        mode = mode,
        lhs = lhs,
        mapping = exact,
      }
    end

    for _, prefix in ipairs(group_prefixes(lhs)) do
      local prefix_map = maparg(prefix, mode)
      if prefix_map and not is_which_key_trigger(prefix_map) then
        result.blocked[#result.blocked + 1] = {
          mode = mode,
          lhs = prefix,
          mapping = prefix_map,
        }
      end
    end
  end

  return result
end

local function remove_generated_bind(data, lhs, modes)
  local requested = {}
  for _, mode in ipairs(modes) do
    requested[mode] = true
  end

  local kept = {}
  for _, bind in ipairs(data.binds or {}) do
    local overlaps = bind.lhs == lhs
    if overlaps then
      overlaps = false
      for _, mode in ipairs(mode_list(bind)) do
        if requested[mode] then
          overlaps = true
          break
        end
      end
    end

    if not overlaps then
      kept[#kept + 1] = bind
    end
  end
  data.binds = kept
end

local function resolve_bind(bind)
  local action = bind.action and state.actions_by_id[bind.action] or nil
  local rhs = bind.rhs or (action and action.rhs)
  local desc = bind.desc or (action and action.desc) or bind.action or bind.lhs

  -- Persisted user-command actions should not depend on registry timing. Some
  -- plugin commands are only visible after their plugin/setup code runs, but a
  -- generated `command.Foo` entry can still safely become `<cmd>Foo<CR>`.
  if not rhs and type(bind.action) == "string" then
    local command = bind.action:match("^command%.(.+)$")
    if command then
      rhs = cmd(command)
      desc = bind.desc or command
    end
  end

  return action, rhs, desc
end

local function apply_bind(bind)
  local action, rhs, desc = resolve_bind(bind)
  if not rhs then
    notify("skipping " .. bind.lhs .. ": missing action " .. tostring(bind.action), vim.log.levels.WARN)
    return
  end

  for _, mode in ipairs(mode_list(bind, action)) do
    vim.keymap.set(mode, bind.lhs, rhs, {
      silent = bind.silent ~= false,
      desc = desc,
    })
  end
end

local function apply_generated(data)
  register_groups(data)
  for _, bind in ipairs(data.binds or {}) do
    apply_bind(bind)
  end
end

function M.generated_path()
  return state.opts.generated_path
end

function M.reload()
  refresh_actions()
  state.generated = load_generated()
  apply_generated(state.generated)
  notify("reloaded " .. state.opts.generated_path)
end

function M.edit_generated()
  vim.cmd.edit(vim.fn.fnameescape(state.opts.generated_path))
end

function M.list_generated()
  local data = load_generated()
  local lines = {
    "# QuickBind prototype state",
    "",
    "Generated file: `" .. state.opts.generated_path .. "`",
    "",
    "## Groups",
  }

  if #data.groups == 0 then
    lines[#lines + 1] = "- none"
  else
    for _, group in ipairs(data.groups) do
      lines[#lines + 1] = ("- `%s` — %s"):format(display_lhs(group.lhs), group.desc)
    end
  end

  lines[#lines + 1] = ""
  lines[#lines + 1] = "## Binds"

  if #data.binds == 0 then
    lines[#lines + 1] = "- none"
  else
    for _, bind in ipairs(data.binds) do
      local action, rhs, desc = resolve_bind(bind)
      lines[#lines + 1] = ("- `%s` [%s] → %s `%s`"):format(
        display_lhs(bind.lhs),
        table.concat(mode_list(bind, action), ""),
        rhs and desc or "missing action",
        bind.action or bind.rhs or "?"
      )
    end
  end

  vim.cmd("vnew")
  local buf = vim.api.nvim_get_current_buf()
  vim.api.nvim_buf_set_name(buf, "QuickBind prototype state")
  vim.api.nvim_set_option_value("buftype", "nofile", { buf = buf })
  vim.api.nvim_set_option_value("bufhidden", "wipe", { buf = buf })
  vim.api.nvim_set_option_value("swapfile", false, { buf = buf })
  vim.api.nvim_set_option_value("filetype", "markdown", { buf = buf })
  vim.api.nvim_buf_set_lines(buf, 0, -1, false, lines)
end

function M.delete_bind()
  run_async(function()
    local data = load_generated()
    if #data.binds == 0 then
      notify("no generated bindings to delete")
      return
    end

    local bind = select_async("Delete generated quickbind", data.binds, function(item)
      return ("%-12s %-6s %s"):format(display_lhs(item.lhs), table.concat(mode_list(item), ""),
        item.desc or item.action or item.rhs)
    end)
    if not bind then
      return
    end

    local choice = confirm_async("Delete " .. display_lhs(bind.lhs) .. "?", { "Cancel", "Delete" })
    if choice ~= "Delete" then
      return
    end

    remove_generated_bind(data, bind.lhs, mode_list(bind))
    write_generated(data)

    for _, mode in ipairs(mode_list(bind)) do
      pcall(vim.keymap.del, mode, bind.lhs)
    end

    state.generated = data
    apply_generated(data)
    notify("deleted " .. display_lhs(bind.lhs) .. "; restart if this had overridden a hand-written map")
  end)
end

local function filtered_actions(query)
  query = trim(query):lower()
  if query == "" then
    return state.actions
  end

  local result = {}
  for _, action in ipairs(state.actions) do
    local haystack = table.concat({ action.id or "", action.desc or "", action.category or "" }, " "):lower()
    if haystack:find(query, 1, true) then
      result[#result + 1] = action
    end
  end
  return result
end

function M.bind(opts)
  opts = opts or {}

  run_async(function()
    refresh_actions()
    local candidates = filtered_actions(opts.query or "")
    if #candidates == 0 then
      notify("no matching actions")
      return
    end

    local action = #candidates == 1 and candidates[1]
        or select_async("QuickBind: choose action", candidates, action_label)
    if not action then
      return
    end

    local default_modes = table.concat(mode_list(action), "")
    local mode_input = input_async("Mode(s) for “" .. action.desc .. "”: ", default_modes)
    if mode_input == nil then
      return
    end

    local modes, mode_error = parse_modes(mode_input, default_modes)
    if not modes then
      notify(mode_error, vim.log.levels.ERROR)
      return
    end

    local lhs_input = input_async("Key sequence (e.g. ff, SPC f f, <leader>ff): ", "")
    if lhs_input == nil then
      return
    end

    local lhs = normalize_lhs(lhs_input)
    if not lhs then
      return
    end

    local validation = validate_lhs(lhs, modes)
    if #validation.blocked > 0 then
      local first = validation.blocked[1]
      notify(
        ("cannot use %s because prefix %s [%s] is already mapped to %s"):format(
          display_lhs(lhs),
          display_lhs(first.lhs),
          first.mode,
          map_summary(first.mapping)
        ),
        vim.log.levels.ERROR
      )
      return
    end

    if #validation.exact > 0 and not opts.force then
      local summaries = {}
      for _, conflict in ipairs(validation.exact) do
        summaries[#summaries + 1] = ("%s [%s] → %s"):format(display_lhs(conflict.lhs), conflict.mode,
          map_summary(conflict.mapping))
      end
      local choice = confirm_async("Override existing mapping? " .. table.concat(summaries, "; "),
        { "Cancel", "Override" })
      if choice ~= "Override" then
        return
      end
    end

    local data = load_generated()
    local groups = generated_group_map(data)
    for _, prefix in ipairs(group_prefixes(lhs)) do
      if not groups[prefix] then
        local desc = input_async("Description for group " .. display_lhs(prefix) .. ": ",
          tokens(prefix)[#tokens(prefix)] or prefix)
        if desc == nil then
          return
        end
        desc = trim(desc)
        if desc == "" then
          desc = display_lhs(prefix)
        end
        add_group(data, prefix, desc)
        groups[prefix] = desc
      end
    end

    remove_generated_bind(data, lhs, modes)
    data.binds[#data.binds + 1] = {
      lhs = lhs,
      modes = modes,
      action = action.id,
      desc = action.desc,
    }

    write_generated(data)
    state.generated = data
    apply_generated(data)

    notify(("bound %s [%s] → %s"):format(display_lhs(lhs), table.concat(modes, ""), action.desc))
  end)
end

local function command_complete(arglead)
  refresh_actions()
  local matches = {}
  local needle = trim(arglead):lower()
  for _, action in ipairs(state.actions) do
    if needle == "" or action.id:lower():find(needle, 1, true) or action.desc:lower():find(needle, 1, true) then
      matches[#matches + 1] = action.id
    end
  end
  return matches
end

local function create_commands()
  vim.api.nvim_create_user_command("QuickBind", function(args)
    M.bind({
      force = args.bang,
      query = args.args,
    })
  end, {
    bang = true,
    nargs = "*",
    complete = command_complete,
    desc = "Prototype: bind an action to a leader key",
  })

  vim.api.nvim_create_user_command("QuickBindDelete", M.delete_bind, {
    desc = "Prototype: delete a generated quickbind",
  })

  vim.api.nvim_create_user_command("QuickBindEdit", M.edit_generated, {
    desc = "Prototype: edit generated quickbinds",
  })

  vim.api.nvim_create_user_command("QuickBindList", M.list_generated, {
    desc = "Prototype: list generated quickbinds",
  })

  vim.api.nvim_create_user_command("QuickBindReload", M.reload, {
    desc = "Prototype: reload generated quickbinds",
  })
end

local function setup_keymaps()
  vim.keymap.set("n", "<leader>kb", M.bind, { silent = true, desc = "Quick bind action" })
  vim.keymap.set("n", "<leader>kd", M.delete_bind, { silent = true, desc = "Delete generated quickbind" })
  vim.keymap.set("n", "<leader>ke", M.edit_generated, { silent = true, desc = "Edit generated quickbinds" })
  vim.keymap.set("n", "<leader>kl", M.list_generated, { silent = true, desc = "List generated quickbinds" })
  vim.keymap.set("n", "<leader>kr", M.reload, { silent = true, desc = "Reload generated quickbinds" })
end

function M.setup(opts)
  state.opts = vim.tbl_deep_extend("force", defaults, opts or {})

  create_commands()
  setup_keymaps()
  refresh_actions()

  state.generated = load_generated()
  apply_generated(state.generated)
end

return M
