-- PROTOTYPE GENERATED by :QuickBind.
--
-- Safe to inspect, but prefer changing entries through :QuickBind, :QuickBindDelete,
-- :QuickBindEdit, and :QuickBindReload. The quickbinder rewrites this whole file.

return {
  version = 1,
  groups = {
  },
  binds = {
    { lhs = "<leader>L", modes = { "n", "x" }, action = "command.Lazy", desc = "Lazy" },
  },
}
