-- PROTOTYPE GENERATED by :QuickBind.
--
-- Safe to inspect, but prefer changing entries through :QuickBind, :QuickBindDelete,
-- :QuickBindEdit, and :QuickBindReload. The quickbinder rewrites this whole file.

return {
  version = 1,
  groups = {
    { lhs = "<leader>g", desc = "go" },
  },
  binds = {
    { lhs = "<leader>L",     modes = { "n", "x" }, action = "command.Lazy",       desc = "Lazy" },
    { lhs = "<leader>gh",    modes = { "n", "x" }, action = "command.Dashboard",  desc = "Dashboard" },
    { lhs = "<leader><tab>", modes = { "n", "x" }, action = "command.BufferPick", desc = "BufferPick" },
    { lhs = "<leader>-",     modes = { "n", "x" }, action = "command.Restart",    desc = "Restart Neovim" },
  },
}
