#!/bin/sh

set -e # exit on error

pushd ~/dotfiles/nixos/
git diff -U0 *.nix
echo "NixOS Rebuilding..."
sudo nixos-rebuild switch --flake ~/dotfiles/nixos#nixos &>nixos-switch.log || ( cat nixos-switch.log | grep --color error && exit 1 )

current=$(sudo nix-env --list-generations --profile /nix/var/nix/profiles/system | grep current)
gen=$(echo $current | awk '{print $1}')

git commit -am "generation $gen"

popd # back to where you were

notify-send -e "NixOS Rebuild Success!"
